import { Product } from './types';

// Mock data for products
export const PRODUCTS: Product[] = [
  // --- WALL UNITS (MURAL) ---
  {
    id: 'daikin-ururu',
    name: 'Ururu Sarara',
    series: 'Daikin',
    type: 'wall',
    image: 'https://i.postimg.cc/3RJSLYPr/ftxz25nv1b-closeup-01.webp?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 3200,
    energyLabel: 'A+++',
    stars: 5,
    minSurface: 20,
    maxSurface: 50,
    dimensions: '295 x 798 x 372 mm',
    features: ['Purifie, humidifie et déshumidifie', 'Fluide R32']
  },
  {
    id: 'daikin-emura',
    name: 'Emura 3',
    series: 'Daikin',
    type: 'wall',
    image: 'https://i.postimg.cc/2SR0s4PF/ftxj-aw-detail-left2.jpg?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 2500,
    energyLabel: 'A+++',
    stars: 5,
    minSurface: 15,
    maxSurface: 50,
    dimensions: '305 x 900 x 212 mm',
    features: ['Design incurvé', 'Nécessite 90cm de largeur', 'Fluide R32']
  },
  {
    id: 'daikin-stylish',
    name: 'Stylish',
    series: 'Daikin',
    type: 'wall',
    image: 'https://i.postimg.cc/RqrTzBbC/ftxa20b2v1bs-closeup-03.webp?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 2100,
    energyLabel: 'A+++',
    stars: 5,
    minSurface: 15,
    maxSurface: 50,
    dimensions: '295 x 798 x 189 mm',
    features: ['Ultra compact en profondeur (18,9cm)', 'Fluide R32']
  },
  {
    id: 'daikin-perfera-wall',
    name: 'Perfera Mural',
    series: 'Daikin',
    type: 'wall',
    image: 'https://i.postimg.cc/8zSqRQPS/ftxm-r-left.jpg?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 1800,
    energyLabel: 'A+++',
    stars: 5,
    minSurface: 15,
    maxSurface: 70,
    dimensions: '295 x 778 x 272 mm',
    features: ['Format standard', 'Idéal pour tout projet', 'Fluide R32']
  },
  {
    id: 'daikin-sensira',
    name: 'Sensira',
    series: 'Daikin',
    type: 'wall',
    image: 'https://i.postimg.cc/rmBhqxDT/02-cold-packshot-ftxf-e-1-1-right.jpg?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 1400,
    energyLabel: 'A+',
    stars: 3,
    minSurface: 15,
    maxSurface: 60,
    dimensions: '286 x 770 x 225 mm',
    features: ['Excellent rapport qualité/prix', 'Fluide R32']
  },
  {
    id: 'mit-ay',
    name: 'MSZ-AY (Premium)',
    series: 'Mitsubishi',
    type: 'wall',
    image: 'https://i.postimg.cc/wxD2htts/684aa1b4ab6ec25763c42992-climatiseur-mitsubishi-inverter-msz-ay.webp?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 1900,
    energyLabel: 'A+++',
    stars: 5,
    minSurface: 15,
    maxSurface: 50,
    dimensions: '299 x 798 x 245 mm',
    features: ['Silence record (18dB)', 'Filtre Plasma Quad', 'Fluide R32']
  },
  {
    id: 'mit-hr',
    name: 'MSZ-HR (Essentiel)',
    series: 'Mitsubishi',
    type: 'wall',
    image: 'https://i.postimg.cc/h488XHw8/mitsu-msz-hr.jpg?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 1500,
    energyLabel: 'A++',
    stars: 3,
    minSurface: 15,
    maxSurface: 70,
    dimensions: '280 x 838 x 228 mm',
    features: ['Spécial "Haut de porte"', 'Hauteur réduite', 'Fluide R32']
  },
  {
    id: 'samsung-windfree',
    name: 'Wind-Free Elite',
    series: 'Samsung',
    type: 'wall',
    image: 'https://i.postimg.cc/8PPvjsLs/ar60f07c1awneu-008-l-dynamic-white.png?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 2100,
    energyLabel: 'A++',
    stars: 4,
    minSurface: 20,
    maxSurface: 40,
    dimensions: '299 x 889 x 215 mm',
    features: ['Sans courants d\'air (23 000 micro-trous)', 'Fluide R32']
  },
  {
    id: 'panasonic-etherea',
    name: 'Etherea',
    series: 'Panasonic',
    type: 'wall',
    image: 'https://i.postimg.cc/br6sQHkV/02-Panasonic-new-Etherea-black.jpg?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 1850,
    energyLabel: 'A+++',
    stars: 4,
    minSurface: 15,
    maxSurface: 70,
    dimensions: '295 x 870 x 229 mm',
    features: ['Technologie Nanoe™ X (Air purifié)', 'Fluide R32']
  },
  {
    id: 'toshiba-seiya',
    name: 'Seiya',
    series: 'Toshiba',
    type: 'wall',
    image: 'https://i.postimg.cc/Dw48XG0z/toshiba-mmk-ap0057hp-e-climatiseurs.jpg?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 1600,
    energyLabel: 'A++',
    stars: 3,
    minSurface: 15,
    maxSurface: 70,
    dimensions: '293 x 798 x 230 mm',
    features: ['Batterie hydrophobe autonettoyante', 'Fluide R32']
  },
  {
    id: 'atlantic-takao',
    name: 'Takao (M2/M3)',
    series: 'Atlantic',
    type: 'wall',
    image: 'https://i.postimg.cc/Rh00V6yd/a245af5cda82-takao-m2-face-atlantic.jpg?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 1550,
    energyLabel: 'A++',
    stars: 3,
    minSurface: 15,
    maxSurface: 45,
    dimensions: '270 x 834 x 222 mm',
    features: ['Le plus bas (27cm)', 'Passe partout', 'Fluide R32']
  },
  {
    id: 'lg-artcool',
    name: 'Artcool Gallery',
    series: 'LG',
    type: 'wall',
    image: 'https://i.postimg.cc/XJ4fLLBv/z5tdo2hf1i.webp?auto=format&fit=crop&q=80&w=400&h=400',
    priceStart: 2800,
    energyLabel: 'A++',
    stars: 5,
    minSurface: 15,
    maxSurface: 35,
    dimensions: '600 x 600 x 146 mm',
    features: ['Format cadre photo (carré)', 'Ultra plat', 'Fluide R32']
  },
  {
    id: 'gree-lomo',
    name: 'Lomo',
    series: 'Gree',
    type: 'wall',
    image: 'https://i.postimg.cc/xdt8r3F1/Product1.jpg?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 1300,
    energyLabel: 'A+',
    stars: 3,
    minSurface: 20,
    maxSurface: 70,
    dimensions: '275 x 790 x 200 mm',
    features: ['Mode hors-gel 8°C', 'Pour résidences secondaires', 'Fluide R32']
  },
  {
    id: 'heiwa-kohai',
    name: 'Kõhai',
    series: 'Heiwa',
    type: 'wall',
    image: 'https://i.postimg.cc/fRvmLXgG/img134.jpg?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 1400,
    energyLabel: 'A++',
    stars: 3,
    minSurface: 20,
    maxSurface: 70,
    dimensions: '250 x 773 x 190 mm',
    features: ['Le plus compact en largeur', 'Pour tailles 2.5kW', 'Fluide R32']
  },
  {
    id: 'mhi-diamond',
    name: 'SRK-ZSX Diamond',
    series: 'MHI',
    type: 'wall',
    image: 'https://i.postimg.cc/J4Vk5PwV/1832187921072918.png?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 2300,
    energyLabel: 'A+++',
    stars: 5,
    minSurface: 20,
    maxSurface: 60,
    dimensions: '305 x 920 x 220 mm',
    features: ['Design italien haut de gamme (Milan)', 'Fluide R32']
  },
  {
    id: 'midea-blanc',
    name: 'Blanc Lite',
    series: 'Midea',
    type: 'wall',
    image: 'https://i.postimg.cc/s2XQgLW0/Blanc-Lite-2022.png?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 1200,
    energyLabel: 'A+',
    stars: 3,
    minSurface: 25,
    maxSurface: 70,
    dimensions: '285 x 805 x 194 mm',
    features: ['Mode "Super Cool"', 'Froid immédiat', 'Fluide R410A']
  },
  {
    id: 'airwell-harmonia',
    name: 'Harmonia',
    series: 'Airwell',
    type: 'wall',
    image: 'https://i.postimg.cc/nV7srBXg/harmonia.png?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 1700,
    energyLabel: 'A++',
    stars: 4,
    minSurface: 20,
    maxSurface: 70,
    dimensions: '297 x 802 x 189 mm',
    features: ['Choix de couleurs', 'Gris, Miroir, Blanc', 'Fluide R32']
  },

  // --- CONSOLES (SOL / BAS DE MUR) ---
  {
    id: 'daikin-fvxm',
    name: 'Perfera (FVXM)',
    series: 'Daikin',
    type: 'console',
    image: 'https://i.postimg.cc/R0yFVZ4C/cq5dam-web-1280-1280.jpg?auto=format&fit=crop&q=80&w=400&h=250', // Replace with real console img if avail
    priceStart: 2200,
    energyLabel: 'A++',
    stars: 5,
    minSurface: 20,
    maxSurface: 50,
    dimensions: '600 x 750 x 238 mm',
    features: ['Sortie d\'air par le bas', 'Confort pieds']
  },
  {
    id: 'mit-mfz',
    name: 'MFZ-KT',
    series: 'Mitsubishi',
    type: 'console',
    image: 'https://i.postimg.cc/kXq55Z3g/mfzkww767xh0.webp?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 2100,
    energyLabel: 'A++',
    stars: 4,
    minSurface: 25,
    maxSurface: 50,
    dimensions: '600 x 750 x 215 mm',
    features: ['S\'encastre partiellement dans le mur', 'Discret']
  },
  {
    id: 'samsung-slim',
    name: 'Console Slim',
    series: 'Samsung',
    type: 'console',
    image: 'https://i.postimg.cc/FHqm0Cq8/uk-AC052FBJDEH-EU-004-Front-silver-10039317020098-624-624-PNG.png?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 2000,
    energyLabel: 'A++',
    stars: 5,
    minSurface: 20,
    maxSurface: 50,
    dimensions: '620 x 720 x 199 mm',
    features: ['La plus fine du marché (<20cm)', 'Design épuré']
  },
  {
    id: 'hitachi-shirokuma',
    name: 'Shirokuma',
    series: 'Hitachi',
    type: 'console',
    image: 'https://i.postimg.cc/FK3t3r0R/hitashi-shirokuma.jpg?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 2300,
    energyLabel: 'A+++',
    stars: 5,
    minSurface: 25,
    maxSurface: 60,
    dimensions: '600 x 750 x 215 mm',
    features: ['Performance thermique exceptionnelle en chaud', 'Haut de gamme']
  },
  {
    id: 'airwell-fmd',
    name: 'FMD',
    series: 'Airwell',
    type: 'console',
    image: 'https://i.postimg.cc/mZdnczK9/console-double-flux-avec-filtre-a-charbon-actif-xdl-013094330-product-maxi.jpg?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 1800,
    energyLabel: 'A+',
    stars: 3,
    minSurface: 25,
    maxSurface: 60,
    dimensions: '700 x 600 x 210 mm',
    features: ['Allège plafonnière', 'Pose sol ou plafond']
  },

  // --- DUCTED (GAINABLES) ---
  {
    id: 'daikin-fdxs',
    name: 'FDXS (Slim)',
    series: 'Daikin',
    type: 'ducted',
    image: 'https://i.postimg.cc/zf12mnH9/cq5dam-web-1280-1280.jpg?auto=format&fit=crop&q=80&w=400&h=250', // Placeholder
    priceStart: 2600,
    energyLabel: 'A+',
    stars: 4,
    minSurface: 15,
    maxSurface: 50,
    dimensions: 'Hauteur 200 mm',
    features: ['Idéal couloir', 'Faux-plafond très étroit']
  },
  {
    id: 'daikin-fba',
    name: 'FBA',
    series: 'Daikin',
    type: 'ducted',
    image: 'https://i.postimg.cc/tTBBVwvW/cq5dam-web-1280-1280.jpg?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 3000,
    energyLabel: 'A++',
    stars: 5,
    minSurface: 40,
    maxSurface: 100,
    dimensions: 'Hauteur 245 mm',
    features: ['Haute pression statique', 'Longues gaines possibles']
  },
  {
    id: 'atlantic-shogun',
    name: 'Gamme Shogun',
    series: 'Atlantic',
    type: 'ducted',
    image: 'https://i.postimg.cc/W10S7hYW/gainable-shogun-atlantic.jpg?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 3500,
    energyLabel: 'A+',
    stars: 5,
    minSurface: 40,
    maxSurface: 120,
    dimensions: 'Selon modèle',
    features: ['Régulation pièce par pièce intégrée', 'Confort zonal']
  },
  {
    id: 'mit-pead',
    name: 'PEAD-SP',
    series: 'Mitsubishi',
    type: 'ducted',
    image: 'https://i.postimg.cc/nhfGMnV6/1551-unite-interieure-type-gainable-mitsubishi-electric-pead-rp60jaq.jpg?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 2800,
    energyLabel: 'A',
    stars: 4,
    minSurface: 40,
    maxSurface: 100,
    dimensions: 'Hauteur 250 mm',
    features: ['Compatible gros réseaux', 'Robuste']
  },
  {
    id: 'lg-low-pressure',
    name: 'Basse Pression',
    series: 'LG',
    type: 'ducted',
    image: 'https://i.postimg.cc/8kWHGFNk/lg-low-pressure-ducted-air-conditioner-12000btu-3-5kw.jpg?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 2400,
    energyLabel: 'A+',
    stars: 4,
    minSurface: 15,
    maxSurface: 50,
    dimensions: 'Hauteur 190 mm',
    features: ['Record de finesse (190mm)', 'Idéal hôtellerie']
  },

  // --- AIR-WATER (PAC AIR-EAU) ---
  {
    id: 'hitachi-yutaki',
    name: 'Yutaki S80',
    series: 'Hitachi',
    type: 'air-water',
    image: 'https://i.postimg.cc/kXqxdfTs/pompe-a-chaleur-air-eau-hitachi-yutaki-s80-combi.png?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 9000,
    energyLabel: 'A+++',
    stars: 5,
    minSurface: 100,
    maxSurface: 250,
    dimensions: 'Eau 80°C',
    features: ['Rénovation sur radiateurs fonte', 'Haute Température']
  },
  {
    id: 'panasonic-aquarea',
    name: 'Aquarea',
    series: 'Panasonic',
    type: 'air-water',
    image: 'https://i.postimg.cc/V6XbxCMp/panasonic-aquarea-all-in-one-wh-adc-h3e5-air-to-water-heat-pump-split-9kw-to-16kw-a-240v-50hz-8935-p.jpg?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 8500,
    energyLabel: 'A+++',
    stars: 5,
    minSurface: 80,
    maxSurface: 200,
    dimensions: 'Eau 60°C',
    features: ['Polyvalente', 'Plancher chauffant ou Radiateurs']
  },
  {
    id: 'atlantic-alfea',
    name: 'Alféa Extensa',
    series: 'Atlantic',
    type: 'air-water',
    image: 'https://i.postimg.cc/02kJ4rNc/2e9587df469d-alfea-extensa-ai-r32-atlantic.jpg?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 7500,
    energyLabel: 'A++',
    stars: 4,
    minSurface: 80,
    maxSurface: 160,
    dimensions: 'Eau 55°C',
    features: ['Neuf ou Rénovation légère', 'Moyenne Température']
  },
  {
    id: 'lg-therma',
    name: 'Therma V',
    series: 'LG',
    type: 'air-water',
    image: 'https://i.postimg.cc/RZqJM8Kj/191756-therma-v-pompe-a-chaleur-air-eau-hydrosplit-r32-de-lg-electronics.jpg?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 8000,
    energyLabel: 'A+++',
    stars: 5,
    minSurface: 100,
    maxSurface: 200,
    dimensions: 'Eau 65°C',
    features: ['Performance extrême', 'COP élevé']
  },
  {
    id: 'airwell-wellea',
    name: 'Wellea',
    series: 'Airwell',
    type: 'air-water',
    image: 'https://i.postimg.cc/0Q1z0y3c/split-produit.png?auto=format&fit=crop&q=80&w=400&h=250',
    priceStart: 7800,
    energyLabel: 'A++',
    stars: 4,
    minSurface: 80,
    maxSurface: 180,
    dimensions: 'Eau 60°C',
    features: ['Monobloc ou Bi-bloc', 'Très robuste']
  }
];

export const INITIAL_DATA: any = {
  rooms: null,
  need: null,
  unitType: null,
  surfaceRoom: 35,
  surfaceHouse: 90,
  selectedProduct: null,
  zipCode: '',
  generatorType: null,
  boilerType: null,
  fuelType: null,
  knowsConsumption: null,
  consumptionAmount: '',
  consumptionUnit: 'kWh',
  energyCost: '',
  contact: {
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
    address: '',
    message: ''
  }
};